-- MySQL Script generated by MySQL Workbench
-- Wed Jul 18 10:45:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProductsDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProductsDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProductsDB` DEFAULT CHARACTER SET utf8 ;
USE `ProductsDB` ;

-- -----------------------------------------------------
-- Table `ProductsDB`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProductsDB`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Desciption` TEXT NULL,
  `Price` DOUBLE NULL,
  `Created_At` DATETIME NULL,
  `Updated_At` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProductsDB`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProductsDB`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Created_At` DATETIME NULL,
  `Updated_At` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProductsDB`.`Categorized`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProductsDB`.`Categorized` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ProductId` INT NOT NULL,
  `CategoryId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Belongs_Products_idx` (`ProductId` ASC),
  INDEX `fk_Belongs_Categories1_idx` (`CategoryId` ASC),
  CONSTRAINT `fk_Belongs_Products`
    FOREIGN KEY (`ProductId`)
    REFERENCES `ProductsDB`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Belongs_Categories1`
    FOREIGN KEY (`CategoryId`)
    REFERENCES `ProductsDB`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
